### ISSUE TITLE
Errors when bundling react-geosuggest with Browserify on node 0.10.x

### ISSUE THREAD

**Issue by holic** [ubilabs/react-geosuggest#95]
I have a project that pulls in react-geosuggest via npm. The project is bundled with Browserify + Babelify.

When I bundle this on node 0.10.x, I run into the following error:

```
23:05:12 Error: Cannot find module 'classnames' from '/src/node_modules/react-geosuggest/module'
23:05:12     at /src/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
23:05:12     at process (/src/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
23:05:12     at ondir (/src/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
23:05:12     at load (/src/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
23:05:12     at onex (/src/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
23:05:12     at /src/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
23:05:12     at Object.oncomplete (fs.js:107:15)
```

Bundling works on node v5.1.0, however.

As a workaround on node 0.10.x, I included classnames in our own package.json dependencies and bundling worked.

Happy to provide more details if it would help!

**Comment by ro-ka** [comment]
I moved `classnames` as a real dependency. Should work in old node now, too. Released in `1.18.1`

**Comment by holic** [comment]
Thanks for the quick fix!

On an unrelated note, I've never seen this badge before:
![image](https://cloud.githubusercontent.com/assets/508855/12988753/0f929414-d0b7-11e5-9dba-46f7b582a929.png)

Any idea where that came from?

**Comment by ro-ka** [comment]
You’re welcome!

The badge is there because I’m a member of the @ubilabs org which is the owner of this package. Github seems to have introduced this some weeks ago.

**Comment by holic** [comment]
Neat :+1:
